export default [{
  id: 8612817,
  name: 'Xiaomi 12 5G',
  slug: 'xiaomi-12-5g-base-875187',
  manufacturer: 'Xiaomi',
  model: '12 5G',
  operating_system: 'ANDROID',
  sim_card_capacity: 'Overig',
  refurbished: false,
  has_usp: false,
  has_5g: true,
  has_esim: false,
  colors: [
    'BLAUW',
    'GRIJS',
  ],
  sort_order: 7,
  release_date: '2022-03-16',
  default: 'xiaomi_12-5g_blue-256gb',
  variants: [
    {
      id: 8615355,
      name: 'Xiaomi 12 5G, Gray',
      slug: 'xiaomi_12-5g_gray-256gb',
      next_ship_date: '2022-04-06',
      usp_offer: {},
      attributes: {
        color: 'GRIJS',
        color_code: '#808080',
        color_name: 'Gray',
        memory: '256 GB',
        handset_cat_promotion_sticker: null,
        promotion_label: 'Nu met 32-inch Smart TV en soundbar t.w.v. €578,-',
        promotion_slider_source: 'usp_offer_xiaomi_12',
        promotion_bg_color: 'green',
        handset_cat_promotion_sticker_kz: null,
        promotion_label_kz: null,
        promotion_slider_source_kz: null,
        promotion_bg_color_kz: null,
      },
      ui_suggested_sort_order: 2,
    },
    {
      id: 8615356,
      name: 'Xiaomi 12 5G, Blue',
      slug: 'xiaomi_12-5g_blue-256gb',
      next_ship_date: '2022-04-06',
      usp_offer: {},
      attributes: {
        color: 'BLAUW',
        color_code: '#0000FF',
        color_name: 'Blue',
        memory: '256 GB',
        handset_cat_promotion_sticker: null,
        promotion_label: 'Nu met 32-inch Smart TV en soundbar t.w.v. €578,-',
        promotion_slider_source: 'usp_offer_xiaomi_12',
        promotion_bg_color: 'green',
        handset_cat_promotion_sticker_kz: null,
        promotion_label_kz: null,
        promotion_slider_source_kz: null,
        promotion_bg_color_kz: null,
      },
      ui_suggested_sort_order: 1,
    },
  ],
  attributes: {
    handset_cat_promotion_sticker: null,
    promotion_label: 'Nu met 32-inch Smart TV en soundbar t.w.v. €578,-',
    promotion_slider_source: 'usp_offer_xiaomi_12',
    promotion_bg_color: 'green',
    handset_cat_promotion_sticker_kz: null,
    promotion_label_kz: null,
    promotion_slider_source_kz: null,
    promotion_bg_color_kz: null,
  },
  has_promotion: true,
},
{
  id: 8612821,
  name: 'Samsung Galaxy A53 5G',
  slug: 'samsung-galaxy-a53-5g-base-875198',
  manufacturer: 'Samsung',
  model: 'Galaxy A53 5G',
  operating_system: 'ANDROID',
  sim_card_capacity: 'Overig',
  refurbished: false,
  has_usp: false,
  has_5g: true,
  has_esim: false,
  colors: [
    'BLAUW',
    'ROZE',
    'ZWART',
  ],
  sort_order: 3,
  release_date: '2022-03-17',
  default: 'samsung_galaxy-a53-5g_awesome-black-128gb',
  variants: [
    {
      id: 8615373,
      name: 'Samsung Galaxy A53 5G 128GB, Awesome Peach',
      slug: 'samsung-galaxy-a53-5g-128gb-awesome-peach-875200',
      next_ship_date: '2022-04-01',
      usp_offer: {},
      attributes: {
        color: 'ROZE',
        color_code: '#FFE5B4',
        color_name: 'Awesome Peach',
        memory: '128 GB',
        handset_cat_promotion_sticker: null,
        promotion_label: 'Nu met Galaxy Buds Live  t.w.v. €149,-',
        promotion_slider_source: 'usp_offer_samsun-galaxy-a52',
        promotion_bg_color: 'green',
        handset_cat_promotion_sticker_kz: null,
        promotion_label_kz: null,
        promotion_slider_source_kz: null,
        promotion_bg_color_kz: null,
      },
      ui_suggested_sort_order: 3,
    },
    {
      id: 8615372,
      name: 'Samsung Galaxy A53 5G 128GB, Awesome Blue',
      slug: 'samsung_galaxy-a53-5g_awesome-blue-128gb',
      next_ship_date: '2022-04-01',
      usp_offer: {},
      attributes: {
        color: 'BLAUW',
        color_code: '#A7C6ED',
        color_name: 'Awesome Blue',
        memory: '128 GB',
        handset_cat_promotion_sticker: null,
        promotion_label: 'Nu met Galaxy Buds Live  t.w.v. €149,-',
        promotion_slider_source: 'usp_offer_samsun-galaxy-a52',
        promotion_bg_color: 'green',
        handset_cat_promotion_sticker_kz: null,
        promotion_label_kz: null,
        promotion_slider_source_kz: null,
        promotion_bg_color_kz: null,
      },
      ui_suggested_sort_order: 2,
    },
    {
      id: 8615371,
      name: 'Samsung Galaxy A53 5G 128GB, Awesome Black',
      slug: 'samsung_galaxy-a53-5g_awesome-black-128gb',
      next_ship_date: '2022-04-01',
      usp_offer: {},
      attributes: {
        color: 'ZWART',
        color_code: '#000000',
        color_name: 'Awesome Black',
        memory: '128 GB',
        handset_cat_promotion_sticker: null,
        promotion_label: 'Nu met Galaxy Buds Live  t.w.v. €149,-',
        promotion_slider_source: 'usp_offer_samsun-galaxy-a52',
        promotion_bg_color: 'green',
        handset_cat_promotion_sticker_kz: null,
        promotion_label_kz: null,
        promotion_slider_source_kz: null,
        promotion_bg_color_kz: null,
      },
      ui_suggested_sort_order: 1,
    },
  ],
  attributes: {
    handset_cat_promotion_sticker: null,
    promotion_label: 'Nu met Galaxy Buds Live  t.w.v. €149,-',
    promotion_slider_source: 'usp_offer_samsun-galaxy-a52',
    promotion_bg_color: 'green',
    handset_cat_promotion_sticker_kz: null,
    promotion_label_kz: null,
    promotion_slider_source_kz: null,
    promotion_bg_color_kz: null,
  },
  has_promotion: true,
},
{
  id: 8647083,
  name: 'Apple iPhone SE',
  slug: 'apple-iphone-se-3e-generatie-base',
  manufacturer: 'Apple',
  model: 'iPhone SE',
  operating_system: 'IOS',
  sim_card_capacity: 'Overig',
  refurbished: false,
  has_usp: false,
  has_5g: true,
  has_esim: true,
  colors: [
    'WIT',
    'ZWART',
  ],
  sort_order: 9,
  release_date: '2022-03-11',
  default: 'apple_iphone-se_midnight-64gb',
  variants: [
    {
      id: 8649656,
      name: 'Apple iPhone SE 256GB, Starlight',
      slug: 'apple_iphone-se_starlight-256gb',
      next_ship_date: null,
      usp_offer: {},
      attributes: {
        color: 'WIT',
        color_code: '#f7f2ee',
        color_name: 'Starlight',
        memory: '256 GB',
        handset_cat_promotion_sticker: null,
        promotion_label: null,
        promotion_slider_source: null,
        promotion_bg_color: null,
        handset_cat_promotion_sticker_kz: null,
        promotion_label_kz: null,
        promotion_slider_source_kz: null,
        promotion_bg_color_kz: null,
      },
      ui_suggested_sort_order: 6,
    },
    {
      id: 8649653,
      name: 'Apple iPhone SE 128GB, Starlight',
      slug: 'apple_iphone-se_starlight-128gb',
      next_ship_date: null,
      usp_offer: {},
      attributes: {
        color: 'WIT',
        color_code: '#f7f2ee',
        color_name: 'Starlight',
        memory: '128 GB',
        handset_cat_promotion_sticker: null,
        promotion_label: null,
        promotion_slider_source: null,
        promotion_bg_color: null,
        handset_cat_promotion_sticker_kz: null,
        promotion_label_kz: null,
        promotion_slider_source_kz: null,
        promotion_bg_color_kz: null,
      },
      ui_suggested_sort_order: 5,
    },
    {
      id: 8649650,
      name: 'Apple iPhone SE 64GB, Starlight',
      slug: 'apple_iphone-se_starlight-64gb',
      next_ship_date: 'Leverbaar vanaf half april',
      usp_offer: {},
      attributes: {
        color: 'WIT',
        color_code: '#f7f2ee',
        color_name: 'Starlight',
        memory: '64 GB',
        handset_cat_promotion_sticker: null,
        promotion_label: null,
        promotion_slider_source: null,
        promotion_bg_color: null,
        handset_cat_promotion_sticker_kz: null,
        promotion_label_kz: null,
        promotion_slider_source_kz: null,
        promotion_bg_color_kz: null,
      },
      ui_suggested_sort_order: 4,
    },
    {
      id: 8649655,
      name: 'Apple iPhone SE 256GB, Midnight',
      slug: 'apple_iphone-se_midnight-256gb',
      next_ship_date: null,
      usp_offer: {},
      attributes: {
        color: 'ZWART',
        color_code: '#171e26',
        color_name: 'Midnight',
        memory: '256 GB',
        handset_cat_promotion_sticker: null,
        promotion_label: null,
        promotion_slider_source: null,
        promotion_bg_color: null,
        handset_cat_promotion_sticker_kz: null,
        promotion_label_kz: null,
        promotion_slider_source_kz: null,
        promotion_bg_color_kz: null,
      },
      ui_suggested_sort_order: 3,
    },
    {
      id: 8649652,
      name: 'Apple iPhone SE 128GB, Midnight',
      slug: 'apple_iphone-se_midnight-128gb',
      next_ship_date: null,
      usp_offer: {},
      attributes: {
        color: 'ZWART',
        color_code: '#171e26',
        color_name: 'Midnight',
        memory: '128 GB',
        handset_cat_promotion_sticker: null,
        promotion_label: null,
        promotion_slider_source: null,
        promotion_bg_color: null,
        handset_cat_promotion_sticker_kz: null,
        promotion_label_kz: null,
        promotion_slider_source_kz: null,
        promotion_bg_color_kz: null,
      },
      ui_suggested_sort_order: 2,
    },
    {
      id: 8649649,
      name: 'Apple iPhone SE 64GB, Midnight',
      slug: 'apple_iphone-se_midnight-64gb',
      next_ship_date: 'Leverbaar vanaf half april',
      usp_offer: {},
      attributes: {
        color: 'ZWART',
        color_code: '#171e26',
        color_name: 'Midnight',
        memory: '64 GB',
        handset_cat_promotion_sticker: null,
        promotion_label: null,
        promotion_slider_source: null,
        promotion_bg_color: null,
        handset_cat_promotion_sticker_kz: null,
        promotion_label_kz: null,
        promotion_slider_source_kz: null,
        promotion_bg_color_kz: null,
      },
      ui_suggested_sort_order: 1,
    },
  ],
  attributes: {
    handset_cat_promotion_sticker: null,
    promotion_label: null,
    promotion_slider_source: null,
    promotion_bg_color: null,
    handset_cat_promotion_sticker_kz: null,
    promotion_label_kz: null,
    promotion_slider_source_kz: null,
    promotion_bg_color_kz: null,
  },
  has_promotion: false,
},
{
  id: 8647084,
  name: 'Apple iPhone SE, RED',
  slug: 'apple-iphone-se-3e-generatie-red-base',
  manufacturer: 'Apple',
  model: 'iPhone SE, RED',
  operating_system: 'IOS',
  sim_card_capacity: 'Overig',
  refurbished: false,
  has_usp: false,
  has_5g: true,
  has_esim: true,
  colors: [
    'ROOD',
  ],
  sort_order: 20,
  release_date: '2022-03-11',
  default: 'apple_iphone-se_productred-256gb',
  variants: [
    {
      id: 8649651,
      name: 'Apple iPhone SE 64GB, (PRODUCT)RED',
      slug: 'apple_iphone-se_productred-64gb',
      next_ship_date: null,
      usp_offer: {},
      attributes: {
        color: 'ROOD',
        color_code: '#9c0010',
        color_name: 'PRODUCT(RED)',
        memory: '64 GB',
        handset_cat_promotion_sticker: null,
        promotion_label: null,
        promotion_slider_source: null,
        promotion_bg_color: null,
        handset_cat_promotion_sticker_kz: null,
        promotion_label_kz: null,
        promotion_slider_source_kz: null,
        promotion_bg_color_kz: null,
      },
      ui_suggested_sort_order: 0,
    },
    {
      id: 8649654,
      name: 'Apple iPhone SE 128GB, (PRODUCT)RED',
      slug: 'apple_iphone-se_productred-128gb',
      next_ship_date: null,
      usp_offer: {},
      attributes: {
        color: 'ROOD',
        color_code: '#9c0010',
        color_name: 'PRODUCT(RED)',
        memory: '128 GB',
        handset_cat_promotion_sticker: null,
        promotion_label: null,
        promotion_slider_source: null,
        promotion_bg_color: null,
        handset_cat_promotion_sticker_kz: null,
        promotion_label_kz: null,
        promotion_slider_source_kz: null,
        promotion_bg_color_kz: null,
      },
      ui_suggested_sort_order: 0,
    },
    {
      id: 8649657,
      name: 'Apple iPhone SE 256GB, (PRODUCT)RED',
      slug: 'apple_iphone-se_productred-256gb',
      next_ship_date: null,
      usp_offer: {},
      attributes: {
        color: 'ROOD',
        color_code: '#9c0010',
        color_name: 'PRODUCT(RED)',
        memory: '256 GB',
        handset_cat_promotion_sticker: null,
        promotion_label: null,
        promotion_slider_source: null,
        promotion_bg_color: null,
        handset_cat_promotion_sticker_kz: null,
        promotion_label_kz: null,
        promotion_slider_source_kz: null,
        promotion_bg_color_kz: null,
      },
      ui_suggested_sort_order: 0,
    },
  ],
  attributes: {
    handset_cat_promotion_sticker: null,
    promotion_label: null,
    promotion_slider_source: null,
    promotion_bg_color: null,
    handset_cat_promotion_sticker_kz: null,
    promotion_label_kz: null,
    promotion_slider_source_kz: null,
    promotion_bg_color_kz: null,
  },
  has_promotion: false,
}];
